name: Bug report
description: 버그를 제보합니다.
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 문제
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
    validations:
      required: true
